/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_DayCare;

import javax.swing.JSplitPane;

/**
 *
 * @author kpsingh
 */
public class TeacherJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherJPanel
     */
    JSplitPane splitPane;
    public TeacherJPanel(JSplitPane splitPane) {
        initComponents();
        this.splitPane = splitPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblParentName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblHeadingMain = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtParentName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblGpa = new javax.swing.JLabel();
        lblEmergencyContact = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtGpa = new javax.swing.JTextField();
        txtEmergencyContact = new javax.swing.JTextField();
        lblVaccination = new javax.swing.JLabel();
        lblHapetitisB = new javax.swing.JLabel();
        btnHapetitisYes = new javax.swing.JRadioButton();
        btnHapetitisNo = new javax.swing.JRadioButton();
        lblMeasels = new javax.swing.JLabel();
        btnMeaselsYes = new javax.swing.JRadioButton();
        btnMeaselsNo = new javax.swing.JRadioButton();
        lblPolio = new javax.swing.JLabel();
        btnPolioYes = new javax.swing.JRadioButton();
        btnPolioNo = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(106, 137, 204));

        jPanel1.setBackground(new java.awt.Color(106, 137, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(747, 498));
        jPanel1.setRequestFocusEnabled(false);

        lblName.setText("First Name");

        lblDob.setText("Date Of Birth");

        lblParentName.setText("Emergency Contact Name");

        lblAddress.setText("Wage");

        lblHeadingMain.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblHeadingMain.setText("Teacher Details");

        txtStudentName.setText("jTextField1");

        txtDob.setText("jTextField2");

        txtParentName.setText("jTextField4");

        lblAge.setText("Last Name");

        lblGpa.setText("Immunization");

        lblEmergencyContact.setText("Emergency Contact Number");

        lblDescription.setText("Employee Review");

        txtAge.setText("jTextField6");

        txtGpa.setText("jTextField7");

        txtEmergencyContact.setText("jTextField9");

        lblVaccination.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblVaccination.setText("Immunization :");

        lblHapetitisB.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblHapetitisB.setText("Hapetitis B");

        btnHapetitisYes.setText("Yes");
        btnHapetitisYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapetitisYesActionPerformed(evt);
            }
        });

        btnHapetitisNo.setText("No");
        btnHapetitisNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapetitisNoActionPerformed(evt);
            }
        });

        lblMeasels.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblMeasels.setText("Measels");

        btnMeaselsYes.setText("Yes");
        btnMeaselsYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeaselsYesActionPerformed(evt);
            }
        });

        btnMeaselsNo.setText("No");
        btnMeaselsNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeaselsNoActionPerformed(evt);
            }
        });

        lblPolio.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblPolio.setText("Polio");

        btnPolioYes.setText("Yes");
        btnPolioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolioYesActionPerformed(evt);
            }
        });

        btnPolioNo.setText("No");
        btnPolioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolioNoActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");

        jTextField8.setText("jTextField8");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHapetitisB)
                                .addGap(181, 181, 181))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnSave))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMeasels)
                                        .addGap(168, 168, 168))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnMeaselsYes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMeaselsNo)
                                        .addGap(111, 111, 111)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnPolioYes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPolioNo))
                                    .addComponent(lblPolio)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHapetitisYes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapetitisNo))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVaccination)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDob)
                            .addComponent(lblParentName)
                            .addComponent(lblName)
                            .addComponent(lblAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtParentName)
                    .addComponent(txtDob, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHeadingMain)
                        .addGap(188, 188, 188)
                        .addComponent(btnEdit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmergencyContact)
                            .addComponent(lblGpa)
                            .addComponent(lblAge)
                            .addComponent(lblDescription))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGpa, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(txtEmergencyContact)
                            .addComponent(txtAge)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeadingMain)
                    .addComponent(btnEdit))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGpa)
                    .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblParentName)
                            .addComponent(txtParentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmergencyContact)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddress)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescription))
                        .addGap(77, 77, 77)
                        .addComponent(lblVaccination))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPolio)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHapetitisB)
                        .addComponent(lblMeasels)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPolioYes)
                        .addComponent(btnPolioNo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMeaselsYes)
                        .addComponent(btnMeaselsNo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHapetitisYes)
                        .addComponent(btnHapetitisNo)))
                .addGap(24, 24, 24)
                .addComponent(btnSave)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapetitisYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapetitisYesActionPerformed
        // TODO add your handling code here:
        btnHapetitisNo.setSelected(!btnHapetitisYes.isSelected());
    }//GEN-LAST:event_btnHapetitisYesActionPerformed

    private void btnHapetitisNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapetitisNoActionPerformed
        // TODO add your handling code here:
        btnHapetitisYes.setSelected(!btnHapetitisNo.isSelected());
    }//GEN-LAST:event_btnHapetitisNoActionPerformed

    private void btnMeaselsYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeaselsYesActionPerformed
        // TODO add your handling code here:
        btnMeaselsNo.setSelected(!btnMeaselsYes.isSelected());
    }//GEN-LAST:event_btnMeaselsYesActionPerformed

    private void btnMeaselsNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeaselsNoActionPerformed
        // TODO add your handling code here:
        btnMeaselsYes.setSelected(!btnMeaselsNo.isSelected());
    }//GEN-LAST:event_btnMeaselsNoActionPerformed

    private void btnPolioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolioYesActionPerformed
        // TODO add your handling code here:
        btnPolioNo.setSelected(!btnPolioYes.isSelected());
    }//GEN-LAST:event_btnPolioYesActionPerformed

    private void btnPolioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolioNoActionPerformed
        // TODO add your handling code here:
        btnPolioYes.setSelected(!btnPolioNo.isSelected());
    }//GEN-LAST:event_btnPolioNoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JRadioButton btnHapetitisNo;
    private javax.swing.JRadioButton btnHapetitisYes;
    private javax.swing.JRadioButton btnMeaselsNo;
    private javax.swing.JRadioButton btnMeaselsYes;
    private javax.swing.JRadioButton btnPolioNo;
    private javax.swing.JRadioButton btnPolioYes;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmergencyContact;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JLabel lblHapetitisB;
    private javax.swing.JLabel lblHeadingMain;
    private javax.swing.JLabel lblMeasels;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblParentName;
    private javax.swing.JLabel lblPolio;
    private javax.swing.JLabel lblVaccination;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmergencyContact;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtParentName;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
